plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  govuk-frontend@*:
    dependencies:
      "sass-loader": "*"
    peerDependencies:
      "sass": "*"
