version: '2'

services:
  ${{ values.component_id }}:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      # TODO: change this mapping to map the port your application listens on
      - ${{ values.http_port }}:${{ values.http_port }}
