version: '2'

services:
  {{ cookiecutter.component_id }}:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      # TODO: change this mapping to map the port your application listens on
      - {{ cookiecutter.http_port }}:{{ cookiecutter.http_port }}
